<?php 
if ( ! defined('BASEPATH')) exit('No direct script access allowed');

	class Health_it_query_model extends CI_Model {
		
		
	public function add_feedback(){
			
       $data = array(
			'client_id' => $this->session->userdata('client_id'),
			'ques_1' => $this->input->post('ques_1'), 
			'ques_2' => $this->input->post('ques_2'),
			'financial' => $this->input->post('financial'),
			'finacial_val' => $this->input->post('finacial_val'),
			'appointment' => $this->input->post('appointment'),
			'app_val' => $this->input->post('app_val'),
			'clinic' => $this->input->post('clinic'),
			'clinic_val' => $this->input->post('clinic_val'),
			'staff' => $this->input->post('staff'),
			'staff_val' => $this->input->post('staff_val'),
			'reporting' => $this->input->post('reporting'),
			'reporting_val' => $this->input->post('reporting_val'),
			'referral' => $this->input->post('referral'),
			'referral_val' => $this->input->post('referral_val'),
			'patient' => $this->input->post('patient'),
			'patient_val' => $this->input->post('patient_val'),
			'exercise' => $this->input->post('exercise'),
			'exercise_val' => $this->input->post('exercise_val'),
			'bill_val' => $this->input->post('bill_val'),
			'book_val' => $this->input->post('book_val'),
			'daily_val' => $this->input->post('daily_val'),
			'ref_val' => $this->input->post('ref_val'),
			'clinicc_val' => $this->input->post('clinicc_val'),
			'm_staff_val' => $this->input->post('m_staff_val'),
			'exe_val' => $this->input->post('exe_val'),
			'ass_val' => $this->input->post('ass_val'),
			'bill_val_a' => $this->input->post('bill_val_a'),
			'book_val_a' => $this->input->post('book_val_a'),
			'daily_val_a' => $this->input->post('daily_val_a'),
			'ref_val_a' => $this->input->post('ref_val_a'),
			'clinic_val_a' => $this->input->post('clinic_val_a'),
			'm_staff_val_a' => $this->input->post('m_staff_val_a'),
			'exe_val_a' => $this->input->post('exe_val_a'),
			'ass_val_a' => $this->input->post('ass_val_a'),
			'bill_val_b' => $this->input->post('bill_val_b'),
			'book_val_b' => $this->input->post('book_val_b'),
			'daily_val_b' => $this->input->post('daily_val_b'),
			'ref_val_b' => $this->input->post('ref_val_b'),
			'clinic_val_b' => $this->input->post('clinic_val_b'),
			'm_staff_val_b' => $this->input->post('m_staff_val_b'),
			'exe_val_b' => $this->input->post('exe_val_b'),
			'ass_val_b' => $this->input->post('ass_val_b'),
			'bill_val_c' => $this->input->post('bill_val_c'),
			'book_val_c' => $this->input->post('book_val_c'),
			'daily_val_c' => $this->input->post('daily_val_c'),
			'ref_val_c' => $this->input->post('ref_val_c'),
			'clinic_val_c' => $this->input->post('clinic_val_c'),
			'm_staff_val_c' => $this->input->post('m_staff_val_c'),
			'exe_val_c' => $this->input->post('exe_val_c'),
			'ass_val_c' => $this->input->post('ass_val_c'),
			'bill_val_d' => $this->input->post('bill_val_d'),
			'book_val_d' => $this->input->post('book_val_d'),
			'daily_val_d' => $this->input->post('daily_val_d'),
			'ref_val_d' => $this->input->post('ref_val_d'),
			'clinic_val_d' => $this->input->post('clinic_val_d'),
			'm_staff_val_d' => $this->input->post('m_staff_val_d'),
			'exe_val_d' => $this->input->post('exe_val_d'),
			'ass_val_d' => $this->input->post('ass_val_d'),
			'bill_val_e' => $this->input->post('bill_val_e'),
			'book_val_e' => $this->input->post('book_val_e'),
			'daily_val_e' => $this->input->post('daily_val_e'),
			'ref_val_e' => $this->input->post('ref_val_e'),
			'clinic_val_e' => $this->input->post('clinic_val_e'),
			'm_staff_val_e' => $this->input->post('m_staff_val_e'),
			'exe_val_e' => $this->input->post('exe_val_e'),
			'ass_val_e' => $this->input->post('ass_val_e'),
			'daily_val_f' => $this->input->post('daily_val_f'),
			'book_val_f' => $this->input->post('book_val_f'),
			'm_staff_val_f' => $this->input->post('m_staff_val_f'),
			'exe_val_f' => $this->input->post('exe_val_f'),
			'bill_val_f' => $this->input->post('bill_val_f'),
			'clinic_val_f' => $this->input->post('clinic_val_f'),
			'ass_val_f' => $this->input->post('ass_val_f'),
			'ref_val_f' => $this->input->post('ref_val_f'),
			'bill_val_g' => $this->input->post('bill_val_g'),
			'book_val_g' => $this->input->post('book_val_g'),
			'daily_val_g' => $this->input->post('daily_val_g'),
			'ref_val_g' => $this->input->post('ref_val_g'),
			'clinic_val_g' => $this->input->post('clinic_val_g'),
			'm_staff_val_g' => $this->input->post('m_staff_val_g'),
			'exe_val_g' => $this->input->post('exe_val_g'),
			'ass_val_g' => $this->input->post('ass_val_g'),
			'bill_val_h' => $this->input->post('bill_val_h'),
			'book_val_h' => $this->input->post('book_val_h'),
			'daily_val_h' => $this->input->post('daily_val_h'),
			'ref_val_h' => $this->input->post('ref_val_h'),
			'clinic_val_h' => $this->input->post('clinic_val_h'),
			'm_staff_val_h' => $this->input->post('m_staff_val_h'),
			'exe_val_h' => $this->input->post('exe_val_h'),
			'ass_val_h' => $this->input->post('ass_val_h'),
			'ques_12' => $this->input->post('ques_12'),
			'ques_13' => $this->input->post('ques_13'),
			'ques_14' => $this->input->post('ques_14'),
			'ques_15' => $this->input->post('ques_15'),
			'ques_16' => $this->input->post('ques_16'),
			'ques_17' => $this->input->post('ques_17'),
			'ques_18' => $this->input->post('ques_18'),
			'ques_19' => $this->input->post('ques_19'),
			'ques_20' => $this->input->post('ques_20'),
			'suggestions' => $this->input->post('suggestions'),
			'contact_you' => $this->input->post('contact_you'),
			 
			);
		$this->db->insert('tbl_health_it_query', $data);
		return true; 
		}
		
	}
	
	
	
		